import { useState, useEffect, useRef } from 'react';
import { Play, Pause, Download, Loader as Loader2, Video } from 'lucide-react';

interface AudioPlayerProps { title: string; subtitle: string; audioUrl?: string; coverUrl?: string; duration: number; onVideo?: () => void; }
function formatTime(seconds: number): string { const m = Math.floor(seconds / 60); const s = Math.floor(seconds % 60); return `${m}:${s.toString().padStart(2, '0')}`; }

export function AudioPlayer({ title, subtitle, audioUrl, coverUrl, duration, onVideo }: AudioPlayerProps) {
  const [isPlaying, setIsPlaying] = useState(false); const [elapsed, setElapsed] = useState(0); const [loading, setLoading] = useState(false); const [actualDuration, setActualDuration] = useState(duration); const audioRef = useRef<HTMLAudioElement | null>(null);
  useEffect(() => { if (!audioUrl) return; setLoading(true); const audio = new Audio(audioUrl); audioRef.current = audio; const onLoaded = () => { setLoading(false); setActualDuration(audio.duration || duration); }; const onTimeUpdate = () => setElapsed(audio.currentTime); const onEnded = () => { setIsPlaying(false); setElapsed(0); }; audio.addEventListener('loadedmetadata', onLoaded); audio.addEventListener('timeupdate', onTimeUpdate); audio.addEventListener('ended', onEnded); return () => { audio.pause(); audio.removeEventListener('loadedmetadata', onLoaded); audio.removeEventListener('timeupdate', onTimeUpdate); audio.removeEventListener('ended', onEnded); }; }, [audioUrl, duration]);
  const handlePlayPause = () => { const audio = audioRef.current; if (!audio) return; if (isPlaying) { audio.pause(); setIsPlaying(false); } else { void audio.play(); setIsPlaying(true); } };
  const handleDownload = async () => { if (!audioUrl) return; try { const response = await fetch(audioUrl); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${title || 'musica'}.mp3`; link.click(); URL.revokeObjectURL(url); } catch { window.open(audioUrl, '_blank'); } };
  const progress = actualDuration > 0 ? (elapsed / actualDuration) * 100 : 0;
  return <div className="premium-card mb-4 animate-fade-in"><div className="flex items-center gap-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-gradient-to-br from-lime-300 to-emerald-800">{coverUrl ? <img src={coverUrl} alt="" className="h-full w-full object-cover" /> : <div className="h-full w-full" />}</div><button onClick={handlePlayPause} disabled={loading || !audioUrl} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-lime-300 text-black transition-transform hover:scale-105 disabled:opacity-50">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : isPlaying ? <Pause className="h-5 w-5 fill-current" /> : <Play className="ml-0.5 h-5 w-5 fill-current" />}</button><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{title}</p><p className="truncate text-xs text-white/40">{subtitle}</p></div><div className="flex gap-1"><button onClick={handleDownload} disabled={!audioUrl} aria-label="Baixar MP3" className="icon-button"><Download className="h-4 w-4" /></button>{onVideo && <button onClick={onVideo} aria-label="Criar vídeo com letra" className="icon-button"><Video className="h-4 w-4" /></button>}</div></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-lime-300 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex justify-between font-mono text-[10px] text-white/35"><span>{formatTime(elapsed)}</span><span>{formatTime(actualDuration)}</span></div></div>;
}
